### ISSUE TITLE
Thoughts about image links

### ISSUE THREAD

**Issue by veltall** [definitelyokay/recipe_flavored_markdown#1]
I personally think that images are a core part of a recipe. It's probably not too difficult to manually parse for markdown image links but would you consider making it part of the RFM parser? Something like:

```dart
final nodes = (parser.parse()[0] as Element).children!.cast<Element>();
      expect(
        nodes[0].children![1],
        isA<Hyperlink>().having(
          (q) => q.textContent,
          'textContent',
          'i.imgur.com/Gvifg5f.jpg',
        ),
      );
```

**Comment by jolexxa** [comment]
Hi! I'm very flattered you've found this package and opened an issue. Can you give me a little bit of context?

What kind of markdown would you like it to recognize? Do you want it to recognize markdown image links, or markdown links pointing to images:

```markdown
![alt text](image.jpg)
```

vs:

```markdown
[some text](some image.jpg)
```

It's been a second since I looked at the dart markdown parser this is built on, but I remember that it did quite a lot with regards to parsing links by default.

**Comment by veltall** [comment]
Originally I was thinking of the first option since there is no ambiguity that it is an image resource.

I haven't considered the pros and cons of either option yet and a big part of the reason is I don't have the full picture of how this flavor of markdown will be used by the authors (recipe creators), the consumers (home cooks following the recipes) and the developers (recipe app dev). My current mental picture is something like this:

- Consumer side: there are two kinds of images I find to be useful: decorative banners and instructional visual aid. The first helps me understand what I'm making (I grew up in Asia and have never seen a cinnamon roll, for example), and the second adds value to the recipe as a technical document.

- Author side: (no special considerations so far regarding use of images)

- Developer side: I can build a better looking app if I have image resources. I also want to be able to offer the user two options for the instructions: 1/ a simplified view with just the essential markdown rendered, and 2/ a detailed view with one step per screen, including both the relevant pictures (e.g. what does soft peak look like) and the text.

I do feel like I'm treading into the "feature creep" territory because I don't know exactly what the intention behind RFM is. My thinking is that RFM leverages markdown as a familiar syntax for authors to write in and for developers to parse, thus bridging the gap between the content creators and the content production. However, RFM recipes can also just be rendered as-is and thus offer a simplistic, grandmother's recipe book kind of experience.

**Comment by veltall** [comment]
>  I don't know exactly what the intention behind RFM is

Upon closer reading of the README, I believe the intent behind RFM is a mix of my two conjectures with a heavy leaning towards the first: A programmatically parsable recipe "syntax" that is 1/ familiar, 2/ natural, and 3/ easy to learn, read, and write. In this case, I do feel that parsing image links is a worthwhile feature; it enriches the app experience for both the developer and the consumer.

**Comment by jolexxa** [comment]
@veltall Sorry for the long delay in getting back to you! I am open to more detailed proposals and pull requests for this functionality if you have ideas!

**Comment by veltall** [comment]
Could you direct me to the parser that you used, then? I'm in between jobs right now but when things settle down I'd be happy to put some time into this project 🙂

**Comment by jolexxa** [comment]
Once again, I have to apologize for forgetting to respond in a timely manner.

Basically, the whole project is nothing more than a couple of additional syntaxes/nodes for Dart's markdown parser. Dart's [markdown parser](https://pub.dev/packages/markdown) is very extensible.

https://github.com/definitelyokay/recipe_flavored_markdown/blob/cb1fe7ca42c7fe0505252e0d257c626d561f1398/lib/src/recipe_markdown_parser.dart#L21-L30

**Comment by jptemplin** [comment]
I am the author of Living Cookbook Rescue, a program that helps users with defunct Living Cookbook software export their recipes trapped in the software to other recipe formats. That allows those users to abandon Living Cookbook and move to another recipe program.

www.livingcookbookrescue.com

I currently export the recipes in the following formats:
Living Cookbook .fdx
MasterCook .mz2
Microsoft Word .docx
Plain Text .txt

The first two formats are de-facto standards and practically any recipe software knows how to read them. The Word documents are a convenient archive format. Recipe software comes and goes, but folks will be able to read Word docs for a very long time.

I've been investigating other formats to add. LaTEX is kinda geeky for your typical home cooks (but the output is gorgeous), but this markdown is intriguing to me. It would allow the files to still be human-readable, with the added benefit of enabling nicely-formatted output. It would be another fine future-proof file format (i.e. you'll always be able to read text files).

Recipe images are the tough nut to crack. Recipe software users LOVE having images with their recipes. At the least, one or more images of the finished recipe. But also image(s) attached to the instruction steps (I've attached a Word doc sample of this use case). If you use links, maintaining the markdown files and the separate image files together in a way that doesn't break the links could be a challenge for many non-tech-savvy home cooks (i.e. you're depending on them to maintain the file system arrangement to keep the links valid). My own thinking is to embed them in Base64 encoding. While that makes the files less human-readable (you could put the images at the end of the file to lessen this), and of course the files would be bigger, but that would have the advantage of having everything in one file. The Living Cookbook .fdx format does exactly this (embedding the images in Base64 format).  Incidentally, the MasterCook .mz2 format keeps the images as separate files, but it's actually a zip archive that keeps everything together. There's an XML file in the archive that has all the recipe data and that data contains references to the image files.

The other thing I wanted to add: home cooks want the option of storing multiple recipes in one file when recipes are used as ingredients. An example: apple pie recipe which uses pie crust as an ingredient. The user should have the option to have both recipes together in one file. I don't see anything in this markdown that prohibits this, but it's something you should keep in mind.

[No-Knead Bread.docx](https://github.com/definitelyokay/recipe_flavored_markdown/files/9046613/No-Knead.Bread.docx)

**Comment by jolexxa** [comment]
This package allows users to use image links as normal, since Markdown already supports images:

```md
![description](image-link.jpg)
```

They would just show up as links in the node tree since that's what the [markdown](https://pub.dev/packages/markdown) package does. Recipe flavored markdown is quite simple: it just adds a few extra node types for quantities and a link resolver for links without a url, so that you can link to an ingredient database, render them different, or whatever you like.
